/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PastLazyImport } from './routes/Past.Lazy'
import { Route as OrderLazyImport } from './routes/Order.Lazy'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PastLazyRoute = PastLazyImport.update({
  id: '/Past/Lazy',
  path: '/Past/Lazy',
  getParentRoute: () => rootRoute,
} as any)

const OrderLazyRoute = OrderLazyImport.update({
  id: '/Order/Lazy',
  path: '/Order/Lazy',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/Order/Lazy': {
      id: '/Order/Lazy'
      path: '/Order/Lazy'
      fullPath: '/Order/Lazy'
      preLoaderRoute: typeof OrderLazyImport
      parentRoute: typeof rootRoute
    }
    '/Past/Lazy': {
      id: '/Past/Lazy'
      path: '/Past/Lazy'
      fullPath: '/Past/Lazy'
      preLoaderRoute: typeof PastLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/Order/Lazy': typeof OrderLazyRoute
  '/Past/Lazy': typeof PastLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/Order/Lazy': typeof OrderLazyRoute
  '/Past/Lazy': typeof PastLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/Order/Lazy': typeof OrderLazyRoute
  '/Past/Lazy': typeof PastLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Order/Lazy' | '/Past/Lazy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Order/Lazy' | '/Past/Lazy'
  id: '__root__' | '/' | '/Order/Lazy' | '/Past/Lazy'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  OrderLazyRoute: typeof OrderLazyRoute
  PastLazyRoute: typeof PastLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  OrderLazyRoute: OrderLazyRoute,
  PastLazyRoute: PastLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/Order/Lazy",
        "/Past/Lazy"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/Order/Lazy": {
      "filePath": "Order.Lazy.jsx"
    },
    "/Past/Lazy": {
      "filePath": "Past.Lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
